In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv


In [2]:
df = pd.read_csv('/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
df.duplicated().sum()

0

In [7]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [8]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [9]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [10]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [11]:
df.drop(columns = ['RowNumber' , 'CustomerId' , 'Surname'] , inplace = True)

In [12]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [13]:
df = pd.get_dummies(df , columns = ['Geography' , 'Gender'], drop_first = True )

In [14]:
df.head(2)

CreditScore  Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0          619   42       2      0.00              1          1   
1          608   41       1  83807.86              1          0   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0

In [15]:
X= df.drop('Exited' , axis=1 )
y = df['Exited']

In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test  = train_test_split(X,y,test_size = 0.2, random_state = 1)

In [17]:
X_train.shape , X_test.shape

((8000, 11), (2000, 11))

In [18]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [19]:
X_train_scaled = scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)

In [20]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [21]:
import tensorflow
from tensorflow import keras
from keras.models import  Sequential
from keras.layers import Dense

In [22]:
model = Sequential()
model.add(Dense(3, activation = 'sigmoid' , input_dim = 11))
model.add(Dense(1, activation = 'sigmoid'))

2022-07-13 12:47:28.342054: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 36        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 4         
Total params: 40
Trainable params: 40
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.compile(optimizer = 'Adam' , loss = 'binary_crossentropy')

In [25]:
model.fit(X_train_scaled , y_train , epochs = 10)

2022-07-13 12:47:28.550037: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/10
250/250 [==============================] - 1s 850us/step - loss: 0.9189
Epoch 2/10
250/250 [==============================] - 0s 849us/step - loss: 0.6778
Epoch 3/10
250/250 [==============================] - 0s 887us/step - loss: 0.5568
Epoch 4/10
250/250 [==============================] - 0s 866us/step - loss: 0.5001
Epoch 5/10
250/250 [==============================] - 0s 838us/step - loss: 0.4730
Epoch 6/10
250/250 [==============================] - 0s 842us/step - loss: 0.4587
Epoch 7/10
250/250 [==============================] - 0s 863us/step - loss: 0.4501
Epoch 8/10
250/250 [==============================] - 0s 847us/step - loss: 0.4440
Epoch 9/10
250/250 [==============================] - 0s 839us/step - loss: 0.4395
Epoch 10/10
250/250 [==============================] - 0s 836us/step - loss: 0.4360


In [26]:
model.layers[0].get_weights()

[array([[ 0.06894686,  0.2575991 ,  0.17244269],
        [ 0.5724606 , -1.3285393 ,  1.5090717 ],
        [-0.24261713,  0.00339334, -0.06722707],
        [-0.02894839, -0.70403403, -0.16017208],
        [-0.4720145 , -0.24192046, -0.41348723],
        [ 0.32926765,  0.1183704 , -0.16549769],
        [-0.44366693,  0.709205  , -0.55616057],
        [-0.39178273, -0.12124316,  0.21732637],
        [ 0.42932677, -0.39081267,  0.41200644],
        [ 0.39296085,  0.21214078, -0.1986964 ],
        [-0.7131968 ,  0.3337435 , -0.20920731]], dtype=float32),
 array([-0.6657666,  1.0121536, -0.6250035], dtype=float32)]

In [27]:
model.layers[1].get_weights()

[array([[ 0.5476532],
        [-1.5589068],
        [ 0.6094813]], dtype=float32),
 array([-0.85594004], dtype=float32)]

In [28]:
model.predict(X_test_scaled)

array([[0.13503972],
       [0.16275421],
       [0.14985734],
       ...,
       [0.09108347],
       [0.1503875 ],
       [0.35703242]], dtype=float32)